# Фінальний проект

## 0. Підготовка середовища

In [4]:
# Install PostgreSQL
!apt-get -qq update > /dev/null
!apt-get -qq install -y postgresql > /dev/null
# Start PostgreSQL
!service postgresql start
# Set password for the postgres user
!sudo -u postgres psql -c "ALTER USER postgres PASSWORD 'postgres';"
# Install SQLAlchemy, PostgreSQL driver and other libraries
!pip install -q sqlalchemy psycopg2-binary pandas

W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu noble InRelease' does not seem to provide it (sources.list entry misspelt?)
[ OK ]
ALTER ROLE

Import libraries

In [3]:
import os
import pandas as pd
from sqlalchemy import create_engine, text

Create Database engine

In [5]:
# Create database engine
engine = create_engine(
    "postgresql+psycopg2://postgres:postgres@localhost:5432/postgres"
)
# Test connection
with engine.connect() as connection:
    result = connection.execute(text("SELECT version();"))
    print(result.scalar())

PostgreSQL 16.15 (Ubuntu 16.15-0ubuntu0.24.04.1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 13.3.0-6ubuntu2~24.04.1) 13.3.0, 64-bit

Utility functions

In [21]:
def ex(sql):
    """Виконує команди, які нічого не повертають"""
    with engine.begin() as conn:
        conn.execute(text(sql))
    print("OK")

def q(sql):
    """Виконує SELECT і повертає результат як таблицю pandas"""
    return pd.read_sql(text(sql), engine)

## 1. Завантаження даних

In [2]:
# Завантаження CSV з Google Drive
import os
CSV_PATH = "infectious_cases.csv"
if not os.path.exists(CSV_PATH):
    !gdown 1dQf-uVXzYPYYGgXsG1y4Q1qDdhP2miZl -O infectious_cases.csv

Downloading...
From: https://drive.google.com/uc?id=1dQf-uVXzYPYYGgXsG1y4Q1qDdhP2miZl
To: /content/infectious_cases.csv
100% 541k/541k [00:00<00:00, 95.3MB/s]

Створюємо схему pandemic і робимо її схемою за замовчуванням. Таблиця для сирих даних: усі колонки TEXT, бо пропуски в CSV — це порожні рядки.

In [7]:
ex("""
CREATE SCHEMA IF NOT EXISTS pandemic;

SET search_path TO pandemic;

DROP TABLE IF EXISTS infectious_cases CASCADE;

CREATE TABLE infectious_cases (
    "Entity"               TEXT,
    "Code"                 TEXT,
    "Year"                 TEXT,
    "Number_yaws"          TEXT,
    "polio_cases"          TEXT,
    "cases_guinea_worm"    TEXT,
    "Number_rabies"        TEXT,
    "Number_malaria"       TEXT,
    "Number_hiv"           TEXT,
    "Number_tuberculosis"  TEXT,
    "Number_smallpox"      TEXT,
    "Number_cholera_cases" TEXT
);
""")

OK

Імпорт CSV у pandemic.infectious_cases через pandas + to_sql

In [9]:
df = pd.read_csv(CSV_PATH, dtype=str, keep_default_na=False)
print(df.shape)
df.to_sql("infectious_cases", engine, schema="pandemic", if_exists="append", index=False)
df.head()

(10521, 12)

,Entity,Code,Year,Number_yaws,polio_cases,cases_guinea_worm,Number_rabies,Number_malaria,Number_hiv,Number_tuberculosis,Number_smallpox,Number_cholera_cases
0,Afghanistan,AFG,1980,,6160,0,,,,,,
1,Afghanistan,AFG,1981,,5859,0,,,,,,
2,Afghanistan,AFG,1982,,9730,0,,,,,,
3,Afghanistan,AFG,1983,,13937,0,,,,,,
4,Afghanistan,AFG,1984,,3864,0,,,,,,

Перевірка чи дані імпортнулись коректно

In [10]:
q("""
SELECT * FROM infectious_cases LIMIT 10
""")

,Entity,Code,Year,Number_yaws,polio_cases,cases_guinea_worm,Number_rabies,Number_malaria,Number_hiv,Number_tuberculosis,Number_smallpox,Number_cholera_cases
0,Afghanistan,AFG,1980,,6160,0,,,,,,
1,Afghanistan,AFG,1981,,5859,0,,,,,,
2,Afghanistan,AFG,1982,,9730,0,,,,,,
3,Afghanistan,AFG,1983,,13937,0,,,,,,
4,Afghanistan,AFG,1984,,3864,0,,,,,,
5,Afghanistan,AFG,1985,,13867,0,,,,,,
6,Afghanistan,AFG,1986,,12901,0,,,,,,
7,Afghanistan,AFG,1987,,4396,0,,,,,,
8,Afghanistan,AFG,1988,,2149,0,,,,,,
9,Afghanistan,AFG,1989,,385,0,,,,,,

Огляд даних

In [11]:
q("""
SELECT COUNT(*)                                   AS total_rows,
       COUNT(DISTINCT ("Entity", "Code"))         AS entity_code_pairs,
       MIN("Year"::INT)                           AS min_year,
       MAX("Year"::INT)                           AS max_year,
       COUNT(*) FILTER (WHERE COALESCE("Number_rabies", '') = '') AS rabies_empty
FROM infectious_cases
""")

   total_rows  entity_code_pairs  min_year  max_year  rabies_empty
0       10521                245      1920      2023          3741

## 2. Нормалізація до 3НФ

В оригінальній таблиці пара (Entity, Code) повторюється для кожного року, а Code залежить лише від Entity, а не від ключа (Entity, Year), тобто це транзитивна залежність. Виносимо пару в таблицю entities, а в таблиці показників infectious_cases_normalized лишаємо entity_id (FK). Заодно перетворюємо '' на NULL, а текст — на NUMERIC.

In [13]:
ex("""
DROP TABLE IF EXISTS infectious_cases_normalized;
DROP TABLE IF EXISTS entities;
""")

OK

### 2.1 Унікальні комбінації Entity + Code

Створення і наповнення таблиці entities

In [14]:
ex("""
CREATE TABLE entities (
    id     SERIAL PRIMARY KEY,
    entity TEXT NOT NULL,
    code   TEXT,
    CONSTRAINT entities_entity_code_uq UNIQUE NULLS NOT DISTINCT (entity, code)
);

INSERT INTO entities (entity, code)
SELECT DISTINCT "Entity", NULLIF("Code", '')
FROM infectious_cases
ORDER BY 1, 2;
""")

OK

Перевірка створених даних

In [15]:
q("""
SELECT * FROM entities LIMIT 10
""")

   id                entity  code
0   1           Afghanistan   AFG
1   2                Africa  None
2   3  African Region (WHO)  None
3   4               Albania   ALB
4   5               Algeria   DZA
5   6        American Samoa   ASM
6   7              Americas  None
7   8               Andorra   AND
8   9                Angola   AGO
9  10   Antigua and Barbuda   ATG

### 2.2 Таблиця показників з entity_id

Створення таблиці infectious_cases_normalized

In [17]:
ex("""
CREATE TABLE infectious_cases_normalized (
    id                   SERIAL PRIMARY KEY,
    entity_id            INT NOT NULL REFERENCES entities (id),
    year                 INT NOT NULL,
    number_yaws          NUMERIC,
    polio_cases          NUMERIC,
    cases_guinea_worm    NUMERIC,
    number_rabies        NUMERIC,
    number_malaria       NUMERIC,
    number_hiv           NUMERIC,
    number_tuberculosis  NUMERIC,
    number_smallpox      NUMERIC,
    number_cholera_cases NUMERIC,
    CONSTRAINT cases_entity_year_uq UNIQUE (entity_id, year)
);
""")

OK

Наповнення таблиці

In [18]:
ex("""
INSERT INTO infectious_cases_normalized (
    entity_id, year,
    number_yaws, polio_cases, cases_guinea_worm, number_rabies, number_malaria,
    number_hiv, number_tuberculosis, number_smallpox, number_cholera_cases
)
SELECT e.id,
       ic."Year"::INT,
       NULLIF(ic."Number_yaws", '')::NUMERIC,
       NULLIF(ic."polio_cases", '')::NUMERIC,
       NULLIF(ic."cases_guinea_worm", '')::NUMERIC,
       NULLIF(ic."Number_rabies", '')::NUMERIC,
       NULLIF(ic."Number_malaria", '')::NUMERIC,
       NULLIF(ic."Number_hiv", '')::NUMERIC,
       NULLIF(ic."Number_tuberculosis", '')::NUMERIC,
       NULLIF(ic."Number_smallpox", '')::NUMERIC,
       NULLIF(ic."Number_cholera_cases", '')::NUMERIC
FROM infectious_cases ic
JOIN entities e
  ON e.entity = ic."Entity"
 AND e.code IS NOT DISTINCT FROM NULLIF(ic."Code", '')
ORDER BY e.id, ic."Year"::INT;
""")

OK

Перевірка створених даних

In [19]:
q("""
SELECT * FROM infectious_cases_normalized LIMIT 10
""")

,id,entity_id,year,number_yaws,polio_cases,cases_guinea_worm,number_rabies,number_malaria,number_hiv,number_tuberculosis,number_smallpox,number_cholera_cases
0,1,1,1960,None,NaN,NaN,None,None,None,None,None,887.0
1,2,1,1965,None,NaN,NaN,None,None,None,None,None,218.0
2,3,1,1980,None,6160.0,0.0,None,None,None,None,None,NaN
3,4,1,1981,None,5859.0,0.0,None,None,None,None,None,NaN
4,5,1,1982,None,9730.0,0.0,None,None,None,None,None,NaN
5,6,1,1983,None,13937.0,0.0,None,None,None,None,None,NaN
6,7,1,1984,None,3864.0,0.0,None,None,None,None,None,NaN
7,8,1,1985,None,13867.0,0.0,None,None,None,None,None,NaN
8,9,1,1986,None,12901.0,0.0,None,None,None,None,None,NaN
9,10,1,1987,None,4396.0,0.0,None,None,None,None,None,NaN

In [20]:
q("""
SELECT (SELECT COUNT(*) FROM infectious_cases)            AS original_rows,
       (SELECT COUNT(*) FROM infectious_cases_normalized) AS normalized_rows,
       (SELECT COUNT(*) FROM entities)                    AS entities_rows
""")

   original_rows  normalized_rows  entities_rows
0          10521            10521            245

Кількість рядків в raw-таблиці співпадає із нормалізованою таблицею. Кількість рядків в таблиці entities = 245

## 3. Аналіз даних

AVG, MIN, MAX, SUM для кожної пари Entity + Code, сортування за середнім за спаданням, 10 рядків.

In [24]:
q("""
SELECT e.id                              AS entity_id,
       e.entity,
       e.code,
       ROUND(AVG(c.number_rabies), 2)    AS avg_rabies,
       MIN(c.number_rabies)              AS min_rabies,
       MAX(c.number_rabies)              AS max_rabies,
       ROUND(SUM(c.number_rabies), 2)    AS sum_rabies
FROM infectious_cases_normalized c
JOIN entities e ON e.id = c.entity_id
WHERE c.number_rabies IS NOT NULL       -- лише рядки, де є значення
GROUP BY e.id, e.entity, e.code
ORDER BY avg_rabies DESC
LIMIT 10
""")

,entity_id,entity,code,avg_rabies,min_rabies,max_rabies,sum_rabies
0,241,World,OWID_WRL,20192.37,14075.5080,24744.6580,605771.11
1,120,Lower Middle Income (WB),None,15193.96,10202.5280,19182.7950,455818.78
2,202,South Asia (WB),None,11729.89,7271.2754,15361.8780,351896.66
3,204,South-East Asia Region (WHO),None,11424.33,6806.0127,15641.9580,342729.81
4,77,G20,None,10189.05,6339.0796,13164.8810,305671.38
5,97,India,IND,8599.17,5425.8726,11121.1420,257975.20
6,209,Sub-Saharan Africa (WB),None,4748.27,4356.8184,5017.9770,142448.04
7,3,African Region (WHO),None,4649.70,4283.0730,4917.7840,139491.07
8,121,Low Income (WB),None,3568.11,3014.6170,3873.5330,107043.16
9,58,East Asia & Pacific (WB),None,3427.46,2009.9395,4591.0107,102823.83

Оскільки згідно умови завдання треба виводити лише 10 записів, то висновки будуть будуватись на основі цих записів, а не всієї таблиці.

* У топ-10 потрапила лише одна країна, Індія. Це свідчить про те, що серед країн саме в Індії найбільш поширений сказ. Решта рядків є агрегатами (світ, регіони, групи за доходом, G20).
* Територіально сказ (rabies) найбільше сконцентрований у Південній Азії (avg - 11729.89) та Південно-Східній Азії (avg - 11424.33).
* Хвороба повʼязана із бідністю. У топ-10 зустрічаються Lower Middle Income (WB) та в Low Income (WB) агрегати.

## 4. Колонка різниці в роках

In [25]:
q("""
SELECT c.year,
       MAKE_DATE(c.year, 1, 1)                                          AS year_start_date,
       CURRENT_DATE                                                     AS today,
       EXTRACT(YEAR FROM AGE(CURRENT_DATE, MAKE_DATE(c.year, 1, 1)))::INT AS years_diff
FROM infectious_cases_normalized c
LIMIT 10
""")

   year year_start_date       today  years_diff
0  1960      1960-01-01  2026-10-29          66
1  1965      1965-01-01  2026-10-29          61
2  1980      1980-01-01  2026-10-29          46
3  1981      1981-01-01  2026-10-29          45
4  1982      1982-01-01  2026-10-29          44
5  1983      1983-01-01  2026-10-29          43
6  1984      1984-01-01  2026-10-29          42
7  1985      1985-01-01  2026-10-29          41
8  1986      1986-01-01  2026-10-29          40
9  1987      1987-01-01  2026-10-29          39

## 5. Власні функції

### 5.1 fn_years_since(year): різниця в роках між поточною датою та 1 січня заданого року

In [26]:
ex("""
CREATE OR REPLACE FUNCTION fn_years_since(p_year INT)
RETURNS INT
LANGUAGE sql
STABLE                       -- залежить від CURRENT_DATE
AS $$
    SELECT EXTRACT(YEAR FROM AGE(CURRENT_DATE, MAKE_DATE(p_year, 1, 1)))::INT;
$$;
""")

OK

Перевірка створеної функції із власноруч створеною датою

In [28]:
q("""
SELECT 1991 AS year, MAKE_DATE(1991, 1, 1) AS year_start_date, fn_years_since(1991) AS years_diff
""")

   year year_start_date  years_diff
0  1991      1991-01-01          35

Перевірка створеної функції на таблиці infectious_cases_normalized

In [29]:
q("""
SELECT c.year,
       MAKE_DATE(c.year, 1, 1) AS year_start_date,
       CURRENT_DATE            AS today,
       fn_years_since(c.year)  AS years_diff
FROM infectious_cases_normalized c
LIMIT 10
""")

   year year_start_date       today  years_diff
0  1960      1960-01-01  2026-10-29          66
1  1965      1965-01-01  2026-10-29          61
2  1980      1980-01-01  2026-10-29          46
3  1981      1981-01-01  2026-10-29          45
4  1982      1982-01-01  2026-10-29          44
5  1983      1983-01-01  2026-10-29          43
6  1984      1984-01-01  2026-10-29          42
7  1985      1985-01-01  2026-10-29          41
8  1986      1986-01-01  2026-10-29          40
9  1987      1987-01-01  2026-10-29          39

### 5.2 fn_avg_cases_per_period(cases, divider): середня кількість захворювань за період

Беремо лише записи, де Number_rabies є числом. 12 - місяць, 4 - квартал, 2 - півріччя.

In [30]:
ex("""
CREATE OR REPLACE FUNCTION fn_avg_cases_per_period(p_cases_per_year NUMERIC, p_divider NUMERIC)
RETURNS NUMERIC
LANGUAGE sql
IMMUTABLE
AS $$
    SELECT CASE
               WHEN p_divider IS NULL OR p_divider = 0 THEN NULL   -- захист від ділення на 0
               ELSE ROUND(p_cases_per_year / p_divider, 2)
           END;
$$;
""")

OK

In [31]:
q("""
SELECT ic."Entity",
       ic."Code",
       ic."Year",
       ic."Number_rabies"::NUMERIC                               AS rabies_per_year,
       fn_avg_cases_per_period(ic."Number_rabies"::NUMERIC, 12)  AS avg_per_month,
       fn_avg_cases_per_period(ic."Number_rabies"::NUMERIC, 4)   AS avg_per_quarter,
       fn_avg_cases_per_period(ic."Number_rabies"::NUMERIC, 2)   AS avg_per_half_year
FROM infectious_cases ic
WHERE ic."Number_rabies" ~ '^-?[0-9]+(\.[0-9]+)?([eE][-+]?[0-9]+)?$'
LIMIT 10
""")

<>:10: SyntaxWarning: invalid escape sequence '\.'
<>:10: SyntaxWarning: invalid escape sequence '\.'
/tmp/ipykernel_1892/718194610.py:10: SyntaxWarning: invalid escape sequence '\.'
  WHERE ic."Number_rabies" ~ '^-?[0-9]+(\.[0-9]+)?([eE][-+]?[0-9]+)?$'

,Entity,Code,Year,rabies_per_year,avg_per_month,avg_per_quarter,avg_per_half_year
0,Afghanistan,AFG,1990,2.145772,0.18,0.54,1.07
1,Afghanistan,AFG,1991,2.320975,0.19,0.58,1.16
2,Afghanistan,AFG,1995,3.126361,0.26,0.78,1.56
3,Afghanistan,AFG,1997,3.446122,0.29,0.86,1.72
4,Afghanistan,AFG,1998,3.557025,0.30,0.89,1.78
5,Afghanistan,AFG,1999,3.607037,0.30,0.90,1.80
6,Afghanistan,AFG,2000,3.636235,0.30,0.91,1.82
7,Afghanistan,AFG,2001,3.711832,0.31,0.93,1.86
8,Afghanistan,AFG,2002,3.841707,0.32,0.96,1.92
9,Afghanistan,AFG,2003,3.914814,0.33,0.98,1.96